name: cu_app
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0+1


environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  image_picker: ^1.2.0
  file_picker: ^10.1.2
  open_filex: ^4.7.0
  intl: ^0.20.2
  socket_io_client: ^3.1.2
  dio: ^5.4.3+1
  flutter_local_notifications: ^19.4.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
#This is a comment to force a dependency refresh
